-- Oracle Database Setup Script
-- This script creates the CUSTOMERS table for the Logic App integration

-- Create CUSTOMERS table
CREATE TABLE CUSTOMERS (
    ID NUMBER PRIMARY KEY,
    FULL_NAME VARCHAR2(100) NOT NULL,
    EMAIL_ADDRESS VARCHAR2(100) NOT NULL,
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MODIFIED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create sequence for auto-incrementing ID
CREATE SEQUENCE CUSTOMERS_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

-- Create trigger to auto-populate ID from sequence
CREATE OR REPLACE TRIGGER CUSTOMERS_BIR
BEFORE INSERT ON CUSTOMERS
FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL THEN
        SELECT CUSTOMERS_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
    END IF;
    :NEW.CREATED_DATE := CURRENT_TIMESTAMP;
END;
/

-- Create trigger to update modified date
CREATE OR REPLACE TRIGGER CUSTOMERS_BUR
BEFORE UPDATE ON CUSTOMERS
FOR EACH ROW
BEGIN
    :NEW.MODIFIED_DATE := CURRENT_TIMESTAMP;
END;
/

-- Create indexes for better performance
CREATE INDEX IDX_CUSTOMERS_EMAIL ON CUSTOMERS(EMAIL_ADDRESS);
CREATE INDEX IDX_CUSTOMERS_CREATED ON CUSTOMERS(CREATED_DATE);

-- Insert sample test data (optional)
INSERT INTO CUSTOMERS (FULL_NAME, EMAIL_ADDRESS) VALUES ('Test User', 'test@example.com');

COMMIT;

-- Verify the table structure
SELECT TABLE_NAME, COLUMN_NAME, DATA_TYPE, NULLABLE
FROM USER_TAB_COLUMNS
WHERE TABLE_NAME = 'CUSTOMERS'
ORDER BY COLUMN_ID;

-- Verify sample data
SELECT * FROM CUSTOMERS;

-- Show sequence details
SELECT SEQUENCE_NAME, MIN_VALUE, MAX_VALUE, INCREMENT_BY, LAST_NUMBER
FROM USER_SEQUENCES
WHERE SEQUENCE_NAME = 'CUSTOMERS_SEQ';
